### ISSUE TITLE
国土地理院のaddress-searchから取得する際にIndexErrorが発生する場合がある

### ISSUE THREAD

**Issue by sonyakun** [sonyakun/sonyaEQ#2]
**バグの説明**
国土地理院のaddress-searchから取得する際にIndexErrorが発生する場合がある

**エラー内容**
受信したjson
```json
{
    "_id": "64c8c54851d38bb17b2e8499",
    "code": 551,
    "earthquake": {
        "domesticTsunami": "None",
        "foreignTsunami": "Unknown",
        "hypocenter": {
            "depth": 30,
            "latitude": 37,
            "longitude": 141.7,
            "magnitude": 4.3,
            "name": "福島県沖"
        },
        "maxScale": 20,
        "time": "2023/08/01 17:38:00"
    },
    "issue": {
        "correct": "None",
        "source": "気象庁",
        "time": "2023/08/01 17:41:43",
        "type": "DetailScale"
    },
    "points": [
        {
            "addr": "角田市角田",
            "isArea": false,
            "pref": "宮城県",
            "scale": 20
        },
        {
            "addr": "岩沼市桜",
            "isArea": false,
            "pref": "宮城県",
            "scale": 20
        },
        {
            "addr": "山元町浅生原",
            "isArea": false,
            "pref": "宮城県",
            "scale": 20
        },
        {
            "addr": "白石市亘理町",
            "isArea": false,
            "pref": "宮城県",
            "scale": 10
        },
        {
            "addr": "名取市増田",
            "isArea": false,
            "pref": "宮城県",
            "scale": 10
        },
        {
            "addr": "蔵王町円田",
            "isArea": false,
            "pref": "宮城県",
            "scale": 10
        },
        {
            "addr": "大河原町新南",
            "isArea": false,
            "pref": "宮城県",
            "scale": 10
        },
        {
            "addr": "柴田町船岡",
            "isArea": false,
            "pref": "宮城県",
            "scale": 10
        },
        {
            "addr": "宮城川崎町前川",
            "isArea": false,
            "pref": "宮城県",
            "scale": 10
        },
        {
            "addr": "亘理町悠里",
            "isArea": false,
            "pref": "宮城県",
            "scale": 10
        },
        {
            "addr": "登米市中田町",
            "isArea": false,
            "pref": "宮城県",
            "scale": 10
        },
        {
            "addr": "大崎市田尻",
            "isArea": false,
            "pref": "宮城県",
            "scale": 10
        },
        {
            "addr": "仙台宮城野区五輪",
            "isArea": false,
            "pref": "宮城 県",
            "scale": 10
        },
        {
            "addr": "仙台若林区遠見塚",
            "isArea": false,
            "pref": "宮城県",
            "scale": 10
        },
        {
            "addr": "石巻市桃生町",
            "isArea": false,
            "pref": "宮城県",
            "scale": 10
        },
        {
            "addr": "塩竈市今宮町",
            "isArea": false,
            "pref": "宮城県",
            "scale": 10
        },
        {
            "addr": "松島町高城",
            "isArea": false,
            "pref": "宮城県",
            "scale": 10
        },
        {
            "addr": "利府町利府",
            "isArea": false,
            "pref": "宮城県",
            "scale": 10
        },
        {
            "addr": "白河市新白河",
            "isArea": false,
            "pref": "福島県",
            "scale": 20
        },
        {
            "addr": "白河市 郭内",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "白河市大信",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "田村市大越町",
            "isArea": false,
            "pref": "福島県",
            "scale": 20
        },
        {
            "addr": "田村市船引町",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "田村市常葉町",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "田村市都路町",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "田村市滝根町",
            "isArea": false,
            "pref": "福島 県",
            "scale": 10
        },
        {
            "addr": "福島伊達市霊山町",
            "isArea": false,
            "pref": "福島県",
            "scale": 20
        },
        {
            "addr": "福島伊達市梁 川町",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "福島伊達市月舘町",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "玉川村小高",
            "isArea": false,
            "pref": "福島県",
            "scale": 20
        },
        {
            "addr": "福島市花園町",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "郡山市朝日",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "郡山市開成",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "郡山市湖南町",
            "isArea": false,
            "pref": "福島 県",
            "scale": 10
        },
        {
            "addr": "須賀川市八幡山",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "須賀川市岩瀬支 所",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "須賀川市八幡町",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "二本松市金色",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "二本松市油井",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "二本松市針道",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "本宮市本宮",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "桑折町谷地",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "国見町藤田",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "川俣町五百田",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "大玉村南小屋",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "大玉村玉井",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "鏡石町不時沼",
            "isArea": false,
            "pref": " 福島県",
            "scale": 10
        },
        {
            "addr": "天栄村下松本",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "西郷村熊倉",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "泉崎村泉崎",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "棚倉町棚倉中居野",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "石川町長久保",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "浅川町浅川",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "小野 町中通",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "小野町小野新町",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "いわき市三和町",
            "isArea": false,
            "pref": "福島県",
            "scale": 20
        },
        {
            "addr": "葛尾村落合落合",
            "isArea": false,
            "pref": "福島県",
            "scale": 20
        },
        {
            "addr": "相馬市中村",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "南相馬市原町区三島町",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "南相馬市鹿島区栃窪",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "南相馬市原町区高見町",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "楢葉町北田",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "富岡町本岡",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "川内村上川内小山平",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "川内村上川内早渡",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "大熊町野上",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "大熊町大川原",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "双葉町長塚",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "浪江町幾世橋",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "新地町谷地小屋",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "飯舘村伊丹沢",
            "isArea": false,
            "pref": "福島県",
            "scale": 10
        },
        {
            "addr": "米沢市アルカディア",
            "isArea": false,
            "pref": "山形県",
            "scale": 10
        },
        {
            "addr": "水戸市内原町",
            "isArea": false,
            "pref": "茨城県",
            "scale": 10
        },
        {
            "addr": "笠間市石井",
            "isArea": false,
            "pref": "茨城県",
            "scale": 10
        }
    ],
    "time": "2023/08/01 17:41:44.079",
    "timestamp": {
        "convert": "2023/08/01 17:41:44.065",
        "register": "2023/08/01 17:41:44.079"
    },
    "user_agent": "jmaxml-seis-parser-go, relay, register-api",
    "ver": "20220813"
}
```
```
Traceback (most recent call last):
  File "C:\Users\hm74c\Desktop\sonyaEEWv2\main.py", line 248, in <module>
    asyncio.get_event_loop().run_until_complete(eew.main())
  File "C:\Users\hm74c\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\hm74c\Desktop\sonyaEEWv2\main.py", line 88, in main
    generate = await eew.map_gen(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hm74c\Desktop\sonyaEEWv2\main.py", line 223, in map_gen
    ret = ret.json()[0]["geometry"]["coordinates"]
          ~~~~~~~~~~^^^
IndexError: list index out of range
```

**期待する動作**
エラーが発生せずにノートされる

**システム情報**
動作バージョン(公式MisskeyBot及び公式DiscordBotは基本的に常に最新版を利用しています。):
Python3のバージョン(python --versionで確認できます。): 
ライブラリのバージョン
```
folium: 0.14.0
misskey.py: 4.1.0
websockets: 11.0.3
httpx:  0.24.1
playwright: 1.34.0
```

**Comment by sonyakun** [comment]
#3 で仮修正
